name       : coreutils
version    : '9.1'
release    : 28
source     :
    - https://ftp.gnu.org/gnu/coreutils/coreutils-9.1.tar.xz : 61a1f410d78ba7e7f37a5a4f50e6d1320aca33375484a3255eddf17a38580423
license    : GPL-3.0-or-later
component  : system.base
summary    : GNU core utilities
description: |
    This package contains the basic file, shell and text manipulation utilities which are expected to exist on every operating system.
builddeps  :
    - acl-devel
    - attr-devel
    - gdb # used in test suite
    - strace # used in test suite
    - valgrind # used in test sutie
optimize   :
    - speed
    - lto
setup      : |
    export FORCE_UNSAFE_CONFIGURE=1
    %reconfigure --enable-largefile \
                 --enable-no-install-program=kill,uptime \
                 gl_cv_func_chown_ctime_works=yes

    # FIXME : the chown ctime test passes in all other circumstances,
            : force enable it to resolve T10232.
build      : |
    %make
install    : |
    %make_install

    install -Ddm00755 $installdir/bin
    # usrmerge is clearly not complete.
    for move in basename cat chgrp chmod chown cp cut date dd df \
    dir echo env false link ln ls mkdir mknod mktemp mv \
    nice pwd readlink rm rmdir sleep sort stty sync touch \
    true uname unlink vdir; do \
        mv $installdir/usr/bin/$move $installdir/bin/$move
    done

    for linkage in env cut readlink; do
        ln -sv ../../bin/$linkage $installdir/usr/bin/$linkage
    done
check      : |
    # There are numerous failures which are related to fakeroot preload errors,
    # permission issues related to being in a chroot, mount issues related to being in a chroot,
    # failures related to attempting to chroot while in a chroot, etc.
    # Don't fail the build because of these test failures. For noted failures, see NOTED-FAILS.md

    %make check-very-expensive || :
