name       : coreutils
version    : '8.30'
release    : 22
source     :
    - https://ftp.gnu.org/gnu/coreutils/coreutils-8.30.tar.xz : e831b3a86091496cdba720411f9748de81507798f6130adeaef872d206e1b057
license    :
    - GPL-3.0-or-later
summary    : GNU core utilities
component  : system.base
description: |
    This package contains the basic file, shell and text manipulation
    utilities which are expected to exist on every operating system.

    Specifically, this package includes:
    arch base64 basename cat chcon chgrp chmod chown chroot cksum comm cp
    csplit cut date dd df dir dircolors dirname du echo env expand expr
    factor false flock fmt fold groups head hostid id install join link ln
    logname ls md5sum mkdir mkfifo mknod mktemp mv nice nl nohup nproc od
    paste pathchk pinky pr printenv printf ptx pwd readlink rm rmdir runcon
    sha*sum seq shred sleep sort split stat stty sum sync tac tail tee test
    timeout touch tr true truncate tsort tty uname unexpand uniq unlink
    users vdir wc who whoami yes
builddeps  :
    - acl-devel
    - attr-devel
optimize   :
    - speed
    - lto
setup      : |
    %patch -p1 < $pkgfiles/coreutils-8.27-i18n-1.patch

    export FORCE_UNSAFE_CONFIGURE=1
    %reconfigure --enable-largefile \
                 --enable-no-install-program=kill,uptime
build      : |
    %make
install    : |
    %make_install

    install -D -d -m 00755 $installdir/bin
    # usrmerge is clearly not complete.
    for move in basename cat chgrp chmod chown cp cut date dd df \
    dir echo env false link ln ls mkdir mknod mktemp mv \
    nice pwd readlink rm rmdir sleep sort stty sync touch \
    true uname unlink vdir; do \
        mv $installdir/usr/bin/$move $installdir/bin/$move
    done

    for linkage in env cut readlink; do
        ln -sv ../../bin/$linkage $installdir/usr/bin/$linkage
    done
check      : |
    # FAIL: tests/tail-2/inotify-dir-recreate
    # FAIL: tests/misc/nice
    # FAIL: tests/rm/no-give-up

    #make check
