name        : coreutils
version     : 8.23
release     : 3
source      :
    - http://ftp.gnu.org/gnu/coreutils/coreutils-8.23.tar.xz : ec43ca5bcfc62242accb46b7f121f6b684ee21ecd7d075059bf650ff9e37b82d
license     :
    - GPLv3+
summary     : GNU core utilities
description : |
    This package contains the basic file, shell and text manipulation
    utilities which are expected to exist on every operating system.
    
    Specifically, this package includes:
    arch base64 basename cat chcon chgrp chmod chown chroot cksum comm cp
    csplit cut date dd df dir dircolors dirname du echo env expand expr
    factor false flock fmt fold groups head hostid id install join link ln
    logname ls md5sum mkdir mkfifo mknod mktemp mv nice nl nohup nproc od
    paste pathchk pinky pr printenv printf ptx pwd readlink rm rmdir runcon
    sha*sum seq shred sleep sort split stat stty sum sync tac tail tee test
    timeout touch tr true truncate tsort tty uname unexpand uniq unlink
    users vdir wc who whoami yes
setup      : |
    %patch -p1 <$pkgfiles/coreutils-8.23-i18n-1.patch
    autoreconf -vfi
    export FORCE_UNSAFE_CONFIGURE=1
    %configure --prefix=/usr         \
               --libexecdir=/usr/lib \
               --enable-largefile \
               --enable-no-install-program=kill,uptime
build      : |
    %make
install    : |
    %make_install
    mkdir -p %installroot%/usr/share/doc/coreutils/
    mkdir -p %installroot%/usr/share/info
    cp AUTHORS ChangeLog ChangeLog-2005 ChangeLog-2006 ChangeLog-2007 ChangeLog-2008 NEWS README THANKS TODO %installroot%/usr/share/doc/coreutils/
    mv %installroot%/usr/share/man/coreutils.info %installroot%/usr/share/info/
