name       : coreutils
version    : '8.32'
release    : 24
source     :
    - https://ftp.gnu.org/gnu/coreutils/coreutils-8.32.tar.xz : 4458d8de7849df44ccab15e16b1548b285224dbba5f08fac070c1c0e0bcc4cfa
license    : GPL-3.0-or-later
component  : system.base
summary    : GNU core utilities
description: |
    This package contains the basic file, shell and text manipulation utilities which are expected to exist on every operating system.
builddeps  :
    - acl-devel
    - attr-devel
    - gdb # used in test suite
    - strace # used in test suite
    - valgrind # used in test sutie
optimize   :
    - speed
    - lto
setup      : |
    %apply_patches

    export FORCE_UNSAFE_CONFIGURE=1
    %reconfigure --enable-largefile \
                 --enable-no-install-program=kill,uptime
build      : |
    %make
install    : |
    %make_install

    install -Ddm00755 $installdir/bin
    # usrmerge is clearly not complete.
    for move in basename cat chgrp chmod chown cp cut date dd df \
    dir echo env false link ln ls mkdir mknod mktemp mv \
    nice pwd readlink rm rmdir sleep sort stty sync touch \
    true uname unlink vdir; do \
        mv $installdir/usr/bin/$move $installdir/bin/$move
    done

    for linkage in env cut readlink; do
        ln -sv ../../bin/$linkage $installdir/usr/bin/$linkage
    done
check      : |
    # There are numerous failures which are related to fakeroot preload errors,
    # permission issues related to being in a chroot, mount issues related to being in a chroot,
    # failures related to attempting to chroot while in a chroot, etc.
    # Don't fail the build because of these test failures. For noted failures, see NOTED-FAILS.md

    %make check-very-expensive || :
