name       : coreutils
version    : '9.3'
release    : 29
source     :
    - https://ftp.gnu.org/gnu/coreutils/coreutils-9.3.tar.xz : adbcfcfe899235b71e8768dcf07cd532520b7f54f9a8064843f8d199a904bbaa
license    : GPL-3.0-or-later
component  : system.base
summary    : GNU core utilities
description: |
    This package contains the basic file, shell and text manipulation utilities which are expected to exist on every operating system.
builddeps  :
    - pkgconfig(libacl)
    - pkgconfig(libattr)
    - pkgconfig(libcap)
    - pkgconfig(libcrypto)
    - gdb # used in test suite
    - strace # used in test suite
    - valgrind # used in test sutie
optimize   :
    - speed
    - lto
setup      : |
    %patch -p1 -i $pkgfiles/0001-Disable-tests-that-fail-in-chroot.patch

    %configure --enable-no-install-program=kill,uptime
build      : |
    %make
install    : |
    %make_install

    install -Ddm00755 $installdir/bin
    # usrmerge is clearly not complete.
    for binary in basename cat chgrp chmod chown cp cut date dd df \
    dir echo env false link ln ls mkdir mknod mktemp mv \
    nice pwd readlink rm rmdir sleep sort stty sync touch \
    true uname unlink vdir; do \
        ln -sv /usr/bin/$binary $installdir/bin/$binary
    done
check      : |
    # Breaks several tests, and the test suite for coreutils is generally well-behaved. Disable fakeroot
    unset LD_PRELOAD
    %make check
